### PR TITLE
Fixed #326: WP 5.7 - Drawer & Modal blocks can't be properly selected in the editor

### LINKED ISSUE #326: WP5.7 - BU Pullquote Fatal Error in editor and doesn't render in Frontend
Like issues #322, #323, and #324 the BU Pullquote block is failing to render in the frontend and when reloading the editor is causing the editor to crash and give this error: https://reactjs.org/docs/error-decoder.html?invariant=321

### PR DESCRIPTION
**Pull request by sksaju**
This PR fixes the issue: https://github.com/bu-ist/bu-blocks/issues/328

I've modified the `allowedBlocks` component file to return `const` variable instead of a callable function to fix this issue as 
`<InnerBlocks allowedBlocks={ allowedBlocks() } />` was causing the issue and didn't work with the function.

### CODE REVIEW

**Comment by acketon** [comment]
The selecting of the block is more reliable but the allowed blocks list is not functioning properly and is only allowing these 2 blocks to be inserted for me: 
image

**Comment by acketon** [comment]
> The selecting of the block is more reliable but the allowed blocks list is not functioning properly and is only allowing these 2 blocks to be inserted for me: image

I'm guessing `getBlockTypes()` is running too soon and only some of the blocks have been registered so I'm only seeing those 2 blocks. If I run `wp.blocks.getBlockTypes()` in the console once the editor has loaded then I get a list of about 63 blocks.

**Comment by sksaju** [comment]
> 

Yeah you are right, using `allowedBlocks` function resolves the available block list issue but again arise the selectable issue

**Comment by acketon** [comment]
this was fixed by upgrading the block to Block API 2 I believe. Closing for now.

**Pull request closed without merging**
